### ISSUE TITLE
Unnecessary indexing of humanoid at line 114 in SwordScript.server.lua

### ISSUE THREAD

**Issue by daily3014** [StrangeEggs/TourneySword#2]
you declared humanoid 2 lines ago and then you do character.humanoid, not to mention humanoid could be named differently
in that case you can simply use FindFirstChildOfClass

**Comment by StrangeEggs** [comment]
character.Humanoid is the Humanoid of the player holding the sword, the `humanoid` variable is the Humanoid of the character that was hit, they aren't the same

**Comment by daily3014** [comment]
Oopsies
